version: 2
updates:
  # Enable version updates for npm (root)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "Tanimou"
    assignees:
      - "Tanimou"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"

  # Enable version updates for npm (API workspace)
  - package-ecosystem: "npm"
    directory: "/api"
    schedule:
      interval: "weekly"
      day: "monday" 
      time: "09:15"
    open-pull-requests-limit: 5
    reviewers:
      - "Tanimou"
    assignees:
      - "Tanimou"
    commit-message:
      prefix: "chore(api)"
      prefix-development: "chore(api)"
      include: "scope"

  # Enable version updates for npm (Web workspace)  
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:30"
    open-pull-requests-limit: 5
    reviewers:
      - "Tanimou"
    assignees:
      - "Tanimou" 
    commit-message:
      prefix: "chore(web)"
      prefix-development: "chore(web)"
      include: "scope"

  # Enable security updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "Tanimou"
    assignees:
      - "Tanimou"
    commit-message:
      prefix: "chore(actions)"
      prefix-development: "chore(actions)"
      include: "scope"